services:
  - type: web
    name: line-fractal-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
